const CART_CONSTANTS = {
  ADD_TO_CART: " ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
  CLEAR_CART: "  CLEAR_CART",
};
export default CART_CONSTANTS;
