const CATEGORY_CONSTANTS = {
  LIST_REQUEST: "CATEGORY_LIST_REQUEST",
  LIST_SUCCESS: "CATEGORY_LIST_SUCCESS",
  LIST_FAIL: "CATEGORY_LIST_FAIL",

  CREATE_REQUEST: "CATEGORY_CREATE_REQUEST",
  CREATE_SUCCESS: "CATEGORY_CREATE_SUCCESS",
  CREATE_FAIL: "CATEGORY_CREATE_FAIL",

  UPDATE_REQUEST: "CATEGORY_UPDATE_REQUEST",
  UPDATE_SUCCESS: "CATEGORY_UPDATE_SUCCESS",
  UPDATE_FAIL: "CATEGORY_UPDATE_FAIL",

  DELETE_REQUEST: "CATEGORY_DELETE_REQUEST",
  DELETE_SUCCESS: "CATEGORY_DELETE_SUCCESS",
  DELETE_FAIL: "CATEGORY_DELETE_FAIL",
};

export default CATEGORY_CONSTANTS;
