export const MENU_CONSTANTS = {
  CREATE: {
    REQUEST: "MENU_CREATE_REQUEST",
    SUCCESS: "MENU_CREATE_SUCCESS",
    FAIL: "MENU_CREATE_FAIL",
    RESET: "MENU_CREATE_RESET",
  },
  LIST: {
    REQUEST: "MENU_LIST_REQUEST",
    SUCCESS: "MENU_LIST_SUCCESS",
    FAIL: "MENU_LIST_FAIL",
  },
  DELETE: {
    REQUEST: "MENU_DELETE_REQUEST",
    SUCCESS: "MENU_DELETE_SUCCESS",
    FAIL: "MENU_DELETE_FAIL",
  },
  UPDATE: {
    REQUEST: "MENU_UPDATE_REQUEST",
    SUCCESS: "MENU_UPDATE_SUCCESS",
    FAIL: "MENU_UPDATE_FAIL",
  },
  SINGLE_MENU: {
    REQUEST: "MENU_SINGLE_REQUEST", // Updated for clarity
    SUCCESS: "MENU_SINGLE_SUCCESS",
    FAIL: "MENU_SINGLE_FAIL",
  },
  // You can add more grouped actions if needed
  TOGGLE_AVAILABILITY: {
    REQUEST: "MENU_TOGGLE_AVAILABILITY_REQUEST",
    SUCCESS: "MENU_TOGGLE_AVAILABILITY_SUCCESS",
    FAIL: "MENU_TOGGLE_AVAILABILITY_FAIL",
  },
};
