export const MENU_CONSTANTS = {
  GET_MENU: {
    REQUEST: "GET_MENU_REQUEST",
    SUCCESS: "GET_MENU_SUCCESS",
    FAIL: "GET_MENU_FAIL",
  },

  CREATE_MENU: {
    REQUEST: "CREATE_MENU_REQUEST",
    SUCCESS: "CREATE_MENU_SUCCESS",
    FAIL: "CREATE_MENU_FAIL",
  },

  DELETE_MENU: {
    REQUEST: "DELETE_MENU_REQUEST",
    SUCCESS: "DELETE_MENU_SUCCESS",
    FAIL: "DELETE_MENU_FAIL",
  },
  UPDATE_MENU: {
    REQUEST: "MENU_UPDATE_REQUEST",
    SUCCESS: "MENU_UPDATE_SUCCESS",
    FAIL: "MENU_UPDATE_FAIL",
  },
  SINGLE_MENU: {
    REQUEST: "MENU_SINGLE_REQUEST", // Updated for clarity
    SUCCESS: "MENU_SINGLE_SUCCESS",
    FAIL: "MENU_SINGLE_FAIL",
  },
  // You can add more grouped actions if needed
  TOGGLE_AVAILABILITY: {
    REQUEST: "MENU_TOGGLE_AVAILABILITY_REQUEST",
    SUCCESS: "MENU_TOGGLE_AVAILABILITY_SUCCESS",
    FAIL: "MENU_TOGGLE_AVAILABILITY_FAIL",
  },
};
