// constants/orderConstants.js
export const ORDER_CONSTANTS = {
  // Create Order
  CREATE: {
    REQUEST: "ORDER_CREATE_REQUEST",
    SUCCESS: "ORDER_CREATE_SUCCESS",
    FAIL: "ORDER_CREATE_FAIL",
    RESET: "ORDER_CREATE_RESET",
  },

  // Get All Orders
  GET_ALL: {
    REQUEST: "ORDER_GET_ALL_REQUEST",
    SUCCESS: "ORDER_GET_ALL_SUCCESS",
    FAIL: "ORDER_GET_ALL_FAIL",
  },
  CLEAR_ALL_ORDERS: "CLEAR_ALL_ORDERS",

  // Get My Orders
  GET_MY_ORDERS: {
    REQUEST: "GET_MY_ORDERS_REQUEST",
    SUCCESS: "GET_MY_ORDERS_SUCCESS",
    FAIL: "GET_MY_ORDERS_FAIL",
  },
  GET_DELIVERYBOY_ORDERS: {
    REQUEST: "GET_DELIVERYBOY_ORDERS_REQUEST",
    SUCCESS: "GET_DELIVERYBOY_ORDERS_SUCCESS",
    FAIL: "GET_DELIVERYBOY_ORDERS_FAIL",
  },
  
  GET_USER_ORDERS: {
    REQUEST: "GET_USER_ORDERS_REQUEST",
    SUCCESS: "GET_USER_ORDERS_SUCCESS",
    FAIL: "GET_USER_ORDERS_FAIL",
  },
  // Get Single Order
  GET_SINGLE: {
    REQUEST: "ORDER_GET_SINGLE_REQUEST",
    SUCCESS: "ORDER_GET_SINGLE_SUCCESS",
    FAIL: "ORDER_GET_SINGLE_FAIL",
  },

  // Track Order
  TRACK: {
    REQUEST: "ORDER_TRACK_REQUEST",
    SUCCESS: "ORDER_TRACK_SUCCESS",
    FAIL: "ORDER_TRACK_FAIL",
  },

  // Update Order Status
  UPDATE_STATUS: {
    REQUEST: "ORDER_UPDATE_STATUS_REQUEST",
    SUCCESS: "ORDER_UPDATE_STATUS_SUCCESS",
    FAIL: "ORDER_UPDATE_STATUS_FAIL",
  },

  // Get Orders for Shopkeeper
  GET_SHOPKEEPER_ORDERS: {
    REQUEST: "ORDER_GET_SHOPKEEPER_ORDERS_REQUEST",
    SUCCESS: "ORDER_GET_SHOPKEEPER_ORDERS_SUCCESS",
    FAIL: "ORDER_GET_SHOPKEEPER_ORDERS_FAIL",
  },

  // Confirm Ready for Pickup
  CONFIRM_READY: {
    REQUEST: "ORDER_CONFIRM_READY_REQUEST",
    SUCCESS: "ORDER_CONFIRM_READY_SUCCESS",
    FAIL: "ORDER_CONFIRM_READY_FAIL",
  },

  // Place Order
  PLACE_ORDER: {
    REQUEST: "ORDER_PLACE_ORDER_REQUEST",
    SUCCESS: "ORDER_PLACE_ORDER_SUCCESS",
    FAIL: "ORDER_PLACE_ORDER_FAIL",
  },
};
