const USER = {
  LIST: {
    REQUEST: "USER_LIST_REQUEST",
    SUCCESS: "USER_LIST_SUCCESS",
    FAIL: "USER_LIST_FAIL",
  },
  VERIFY: {
    REQUEST: "USER_VERIFY_REQUEST",
    SUCCESS: "USER_VERIFY_SUCCESS",
    FAIL: "USER_VERIFY_FAIL",
  },
  CURRENT_USER: {
    REQUEST: "USER_CURRENT_REQUEST",
    SUCCESS: "USER_CURRENT_SUCCESS",
    FAIL: "USER_CURRENT_FAIL",
  },
  LOGIN: {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAIL: "USER_LOGIN_FAIL",
  },
  REGISTER: {
    REQUEST: "USER_REGISTER_REQUEST",
    SUCCESS: "USER_REGISTER_SUCCESS",
    FAIL: "USER_REGISTER_FAIL",
  },
  LOGOUT: "LOGOUT",
};

export default USER;
